### ISSUE TITLE
Cannot edit uesr in ActiveAdmin when username contains '.'

### ISSUE THREAD

**Issue by OmeletWithoutEgg** [TIOJ-INFOR-Online-Judge/tioj#22]
As an example, if one visits https://tioj.ck.tp.edu.tw/admin/users/ioi.jqbpzk, he'll get a 406 ERROR. The passenger error log says that it cannot recognize the format (extension).
Also if there's an user whose username ends with `.json`, it'll send a json with 406 error. e.g. https://tioj.ck.tp.edu.tw/users/abc.json

**Comment by adrien1018** [comment]
Fixed on #23.
