### ISSUE TITLE
批量上傳 testcase

### ISSUE THREAD

**Issue by as6325400** [TIOJ-INFOR-Online-Judge/tioj#31]
目前不管是在題目介面上傳，或者是到 admin 裡面的 testcase ，皆只能單筆測資上傳，請問有批量上傳測資的方式嗎？

**Comment by oToToT** [comment]
不太確定現在這個 script 還會不會運作 https://github.com/TIOJ-INFOR-Online-Judge/tioj-scripts/blob/master/testdata_upload_folder.py

**Comment by oToToT** [comment]
不知道 https://github.com/TIOJ-INFOR-Online-Judge/tioj/pull/32 有沒有包含這邊所需的功能?

**Comment by as6325400** [comment]
有的，感謝，然後經過測試那個 script 小改一下後也還能運作

**Comment by adrien1018** [comment]
Added in #32.
